## 数组的创建

In [8]:
import numpy as np
# 创建数组
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [10]:
# 通过python list创建
list_1 = ['a','b','c']
array2 = np.array(list_1)
print(array2)

['a' 'b' 'c']


In [11]:
# 创建二位数组
list_2 = ['d','e','f']
array3 = np.array([arr1,array2])
print(array3)

[['1' '2' '3']
 ['a' 'b' 'c']]


In [12]:
#数组的shape , size
print(array3.shape) # 返回2行3列
print(array3.size) # 6个长度

(2, 3)
6


In [16]:
# 数组的数据类型
print(array2.dtype)
print(arr1.dtype)
array4 = np.array([2,3,4.0])
print(array4.dtype)


<U1
int64
float64


In [17]:
# 通过np.arange创建数组
array5 = np.arange(1,10) # 返回1-10的一维数组
print(array5)
array6 = np.arange(1,10,3) # 返回1-10的一维数组,步长为3. 
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 4 7]


In [19]:
# 创建一个全0数组
zero_array_1 = np.zeros(5) #创建一个1维的全0数组，5个元素
print(zero_array_1)
zero_arra_2 = np.zeros([3,4]) #创建一个3行4列的全0矩阵
print(zero_arra_2)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
# 创建一个单位数组
# 单位数组即对角线元素全为1，其他元素为0
unit_array1 = np.eye(5)
print(unit_array1)
print(unit_array1.dtype)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
float64


## 数组的访问

In [26]:
#访问一维数组
a = np.array([1,2,3,4,5,6])
print(a[1]) # 根据index访问

a[2:4] # 根据范围访问

2


array([3, 4])

In [32]:
# 访问多维数组
b = np.array([[1,2,3],[4,5,6]])
b
# 访问第2行，第3列(6)
b[1][2] # 等价 b[1,2]


6

In [35]:
#多维数组切片
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
c[:2,1:] 
# :2 ,返回第0行到第2行  
# 1: ,返回第2列到最后

array([[2, 3],
       [5, 6]])

In [40]:
c[1:3,0:1] 
# 1:3 ,返回第2行到第3行  
# 0:1 ,返回第1列

array([[4],
       [7]])

In [46]:
# 快速创建数组
random_1 = np.random.randn(10) ## 随机创建10个元素的一维数组
random_1


array([-0.21351738, -0.50766358,  1.86305468, -1.09589387,  1.35627202,
       -1.15981608,  0.60265335,  1.64240241,  0.00475568,  2.31984365])

7

In [59]:
np.random.randint(10 , size=[3,4]) # 随机生成一个3行4列 10以内的数组



array([[2, 6, 5, 3],
       [2, 3, 5, 3],
       [4, 0, 5, 1]])

## 数组与矩阵计算

In [65]:
a = np.random.randint(10, size=20).reshape(4,5)
a

array([[8, 3, 3, 8, 3],
       [8, 5, 6, 8, 2],
       [5, 5, 9, 0, 2],
       [7, 2, 8, 9, 6]])

In [66]:
b= np.random.randint(10, size=20).reshape(4,5)
b

array([[3, 8, 4, 6, 6],
       [1, 9, 1, 4, 6],
       [9, 0, 3, 8, 6],
       [0, 7, 3, 4, 3]])

In [67]:
a+b # 数组的加减法是对矩阵内对应元素的加减乘除

array([[11, 11,  7, 14,  9],
       [ 9, 14,  7, 12,  8],
       [14,  5, 12,  8,  8],
       [ 7,  9, 11, 13,  9]])

In [68]:
a-b

array([[ 5, -5, -1,  2, -3],
       [ 7, -4,  5,  4, -4],
       [-4,  5,  6, -8, -4],
       [ 7, -5,  5,  5,  3]])

In [69]:
a*b

array([[24, 24, 12, 48, 18],
       [ 8, 45,  6, 32, 12],
       [45,  0, 27,  0, 12],
       [ 0, 14, 24, 36, 18]])

In [75]:
c = np.random.randint(10 , size=5)
print(c)
'''
array([[8, 3, 3, 8, 3],
       [8, 5, 6, 8, 2],
       [5, 5, 9, 0, 2],
       [7, 2, 8, 9, 6]])
'''

a.dot(c)

[2 6 1 8 7]


array([122, 130,  63, 148])

In [76]:
a / b

/var/folders/bd/m33253h9065gn76s2j8015340000gn/T/ipykernel_2509/1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([[2.66666667, 0.375     , 0.75      , 1.33333333, 0.5       ],
       [8.        , 0.55555556, 6.        , 2.        , 0.33333333],
       [0.55555556,        inf, 3.        , 0.        , 0.33333333],
       [       inf, 0.28571429, 2.66666667, 2.25      , 2.        ]])

## 矩阵运算


In [79]:
#创建矩阵通过mat()
m = np.mat([[1,2,3],[4,5,6]])
m

matrix([[1, 2, 3],
        [4, 5, 6]])

In [80]:
# 将array转成矩阵
A = np.mat(a)
A

matrix([[8, 3, 3, 8, 3],
        [8, 5, 6, 8, 2],
        [5, 5, 9, 0, 2],
        [7, 2, 8, 9, 6]])

In [81]:
B = np.mat(b)
B

matrix([[3, 8, 4, 6, 6],
        [1, 9, 1, 4, 6],
        [9, 0, 3, 8, 6],
        [0, 7, 3, 4, 3]])

In [82]:
A+B

matrix([[11, 11,  7, 14,  9],
        [ 9, 14,  7, 12,  8],
        [14,  5, 12,  8,  8],
        [ 7,  9, 11, 13,  9]])

In [83]:
A - B

matrix([[ 5, -5, -1,  2, -3],
        [ 7, -4,  5,  4, -4],
        [-4,  5,  6, -8, -4],
        [ 7, -5,  5,  5,  3]])

## Array函数


In [85]:
arr = np.random.randint(10, size=[4,5])  # 等价于 arr = np.random.rantint(10, size=20).reshape(4,5)
arr

array([[7, 7, 8, 0, 3],
       [4, 9, 3, 9, 6],
       [5, 2, 6, 2, 4],
       [2, 0, 7, 2, 3]])

In [87]:
np.unique(arr)  #返回唯一数

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
sum(arr) # 行相加

array([18, 18, 24, 13, 16])

In [90]:
sum(arr[0]) ##返回第一行加和

25

In [91]:
sum(arr[:,0])   # 第一列加和 [:,0]  不指定行，第一列

18

In [93]:
arr.max()


9

In [95]:
max(arr[2]) ##返回第三行最大值

6

In [96]:
max(arr[:,2]) ##返回第三列最大值

8

## 序列化array

In [101]:
import pickle
# 通过传统方式读 写数组到文件
x = np.arange(10)




In [102]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
f = open('x.pickle','wb')
pickle.dump(x,f) #写入到x.pickel文件

In [107]:
!ls
    

numpy.ipynb x.pickle


In [108]:
# 读取文件
f = open('x.pickle','rb')
y = pickle.load(f)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
## 使用numpy方法保存
np.save('write.npy',x)

In [114]:
!ls


numpy.ipynb      write.npy        write.pickle.npy x.pickle


In [115]:
z = np.load('write.npy')

In [116]:
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])